### ISSUE TITLE
Cannot use edit on a website that already uses hashes urls

### ISSUE THREAD

**Issue by fracz** [simplaio/simpla#10]
I am trying to integrate simpla with [Vaadin](https://vaadin.com). It uses hashes in URLs to recognize pages, for example `http://website.com/#!contact`.

I have placed `<simpla-text>` there. I tried going to `http://website.com/#edit` or `http://website.com/#!contact#edit` and the simpla login form appearead correctly. However, Vaadin shows 404 error page for these URLs. When I go back to `http://website.com/#!contact`, I can not edit the contents.

IMHO, once I have authenticated in simpla by going to the `#edit`, there should be a button on every page that enables its editing without changing URL of the application.

**Comment by bedeoverend** [comment]
@fracz we're aware of this bug and looking at a workaround. What we're going to have is a function on our Simpla JS object that you can call to open / close edit mode - basically so you can control how you turn on and off Simpla if you don't want to use hashes.

We don't have a firm ETA on this, but will update here as soon as we have something in the works :)

**Comment by seaneking** [comment]
Going to rename this issue to reflect @bedeoverend's comments

**Comment by seaneking** [comment]
@fracz I agree how we currently handle edit mode isn't ideal - the problem with staying in edit mode across pages/once you've authenticated is that you'd have to logout/login every time you wanted to enter/exit edit mode on your site, which would get frustrating pretty quickly. 

There are other considerations too, for example if you leave a page with unsaved changes, do you lose those changes or does pressing 'save' save content site-wide?

**Comment by fracz** [comment]
Site-wide save would be confusing to me. It should rather warn me before page change that I have some unsaved edits ([`window.onbeforeunload`](https://developer.mozilla.org/pl/docs/Web/API/WindowEventHandlers/onbeforeunload)?). However, it would tricky work for SPAs that use the [HTML5 `pushState()`](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method) because changing view with `pushState()` does not fire `onbeforeunload`. Perhaps, you should listen for [DOM removal events](http://stackoverflow.com/questions/3219758/detect-changes-in-the-dom) of simpla-elements? Just a hunch.

And yes - I meant the toggle button. IMO, when I enter new page, the edit should be disabled by default (event if I have edited the previous one). But instead of "Save" button in the top right corner, there should be an "Edit this page" button if I'm authenticated in Simpla.

**Comment by seaneking** [comment]
Yep I agree (as I think @bedeoverend does) that we wouldn't want to persist unsaved changes across pages. And warning on leaving a page with unsaved changes is already in an issue (https://github.com/simplaio/simpla/issues/13).

Interesting idea re: toggle button if authed. That could potentially be a clean way to handle this and not have to continually enter edit mode.

**Comment by seaneking** [comment]
I've made dedicated issues for all the points raised in this thread:

- #29 
- #28 
- #13 

Follow along in those for progress/discussion. Closing this thread for now.
