### ISSUE TITLE
Multiple history entries for the home page (simpla.io)

### ISSUE THREAD

**Issue by fracz** [simplaio/simpla#12]
When you go to http://simpla.io and click the Simpla logo - page refreshes as expected. But when you do it multiple times...

![image](https://cloud.githubusercontent.com/assets/3918865/15023405/9fd6087a-1230-11e6-9904-35742b0aa734.png)

You must have some weird redirection there :-)

**Comment by bedeoverend** [comment]
@fracz odd! Thanks for reporting - what browser + version / OS are you getting this on? Just trying to replicate on my end.

**Comment by fracz** [comment]
Current chrome, i.e. 50.0.2661.94 m

**Comment by seaneking** [comment]
This was fixed with the rebuild for v1 (https://blog.simpla.io/introducing-simpla-v1-0/)
