### ISSUE TITLE
simple-api attribut deprecated but docs not updated

### ISSUE THREAD

**Issue by Kunamatata** [simplaio/simpla#14]
Hi,

I'm having this message in the developer console but the docs still say to use simpla-api attribut in script tag https://www.simpla.io/docs/

`The [simpla-api] attribute setup method is deprecated. Please use Simpla('rJIj1iC') instead, see https://www.simpla.io/docs/start`

**Comment by seaneking** [comment]
Documentation being updated as we speak :-)

TL;DR; Simpla is now setup with Javascript rather than a script attribute, like so:

```html
<script src="https://app.simpla.io"></script>
<script>
  Simpla('rJIj1iC');
</script>
```

**Comment by seaneking** [comment]
Docs updated

**Comment by Kunamatata** [comment]
Thanks! You guys are great =) Sorry if it was a useless issue

**Comment by seaneking** [comment]
No such thing as a useless issue! The more we hear about the better ;-)

**Comment by giorgiodoueihi** [comment]
Heads up, the docs haven't updated for me. Tried multiple browsers, clearing cache, and private mode. Perhaps a CDN thing?

Also probably a minor thing (considering this is still an early beta), but shouldn't you mask the API key in the console when printing the depreciated method warning, for security purposes?

**Comment by seaneking** [comment]
Harrumph. Iooking into it now.

**Comment by seaneking** [comment]
Fixed
