### ISSUE TITLE
Entering into placeholder and deleting all disables editing on that element

### ISSUE THREAD

**Issue by suyeonson** [simplaio/simpla#16]
I can't tell if this is a new issue. This is the first time I've noticed it happening.

Using the sample template (on latest Chrome), when I enter text then delete the text in an element, I can't re-enter text into that same element. Placeholder text shows up but editing becomes disabled. The blinking cursor appears for a split second before disappearing. Saving also no longer works. Refreshing does not return elements to their original functional state. Only solution seems to log out and back in. No error logs in the console as far as I can tell!

**Comment by seaneking** [comment]
I'd take a stab at this being a sizing issue - when simpla-text is empty it should have the width of the placeholder, but that seems to be broken. I'll have a better look soon.

**Comment by seaneking** [comment]
EDIT: bug confirmed, and not a sizing issue

/cc @bedeoverend

**Comment by bedeoverend** [comment]
@seaneking @suyeonson Looked into this properly - it's specific to inline text elements. Basically an empty inline text element should in fact at least contain a `<br />` (an "empty" block contains `<p></p>`), which is the default empty state with Scribe. For some reason this isn't being applied when it's cleared via the keyboard. Should be fairly easy to patch, I'll update once that's done.

**Comment by bedeoverend** [comment]
This issue was moved to SimplaElements/simpla-text#20
