### ISSUE TITLE
Srcset, sizes, and/or the picture element

### ISSUE THREAD

**Issue by d3ddd** [simplaio/simpla#25]
It would really help with responsive images if we could take advantage of srcset, sizes, and/or the picture element. 

It's great that I can build a site essentially anyway I want and then hand it off to a client and they can edit it with virtually no training.

However, I can't seem to figure out a way that I could still have responsive image files using picturefill while using simpla.

That's something I'd REALLY like to be able to do!

**Comment by bedeoverend** [comment]
@d3ddd so right now we don't support the `srcset` attribute, but it's something we definitely want to add in the future. We're also looking into extending `<img>` (rather than just defining `<simpla-img>`) which would help us significantly in supporting these new features.

Thanks for the feedback!

**Comment by bedeoverend** [comment]
This issue was moved to SimplaElements/simpla-img#32
