### ISSUE TITLE
<simpla-text> inside <a> tags

### ISSUE THREAD

**Issue by ishmangit** [simplaio/simpla#26]
This comment is quite similar to @fracz about hashes urls, but a little more worrying because is not possible to edit "simpla-text" tags that are inside "a href=""..." of any kind...
Simply editing mode is lost trying to follow the link when you try to edit the text.

Otherwise I think it's very good tool and I will keep an eye on it ;)

**Comment by bedeoverend** [comment]
@ishmangit thanks for flagging this. Plan is to add an option to disable links while in edit mode, with the ability to quickly toggle this on and off via a button / hotkey. That way if its an SPA and you need the link to take you somewhere else to update content, you'd be able to do that without reloading the entire page.

Don't have a solid timeline around this right now, but will keep you posted.

**Comment by seaneking** [comment]
This will be fixed in #28. Closing this for now, follow that issue for progress :-)
