### ISSUE TITLE
Support for SPA frameworks specifically Aurelia

### ISSUE THREAD

**Issue by VagyokC4** [simplaio/simpla#3]
I use Aurelia (http://aurelia.io) for building SPA apps.  Because you use the #edit function to toggle edit mode, it seems to conflict with the Aurelia router as SPA pages use the #<route> to navigate the site.

How can we get Simpla working inside an SPA?

**Comment by seaneking** [comment]
Yep making the Simpla admin modules (edit mode, save, auth, etc) customisable/optional is on the roadmap. 

We'll likely provide a Js method to trigger edit mode, and allow you to disable the #edit trigger. No firm ETA yet - is this an urgent feature for you?

**Comment by VagyokC4** [comment]
Yes, all my web work is done with Aurelia lately.

**Comment by VagyokC4** [comment]
Do we have an ETA for this?  I'd like to start playing with Simpla in my Aurelia apps?

**Comment by seaneking** [comment]
@VagyokC4 unfortunately no ETA yet. If you want to get this working now as a temporary solution though you can trigger edit mode through the `sm-admin` element that is injected into the page - it has an `_edit` property, which when set to true will start up edit mode. e.g. `document.querySelector('sm-admin')._edit = true;` 

This will have to be done on every hashchange, as `sm-admin` looks for `#edit`. Also I don't recommend using this as a stable solution as it's a private property, which could likely change it in the future.

**Comment by seaneking** [comment]
Done! We've added a public method to the global `simpla` object that exists when you include Simpla - `editMode(state)`. So you can now enter edit mode by just calling `simpla.editMode(true)`. While edit mode is true all hashchanges will be ignored by Simpla.

**Comment by VagyokC4** [comment]
I get the following error:  => simpla.editMode is not a function

**Comment by seaneking** [comment]
Sorry about that, we've had to roll this back temporarily while we fix a regression it introduced. Should be back up soon. I'll reopen this issue until then.

**Comment by seaneking** [comment]
Fixed :-)

**Comment by VagyokC4** [comment]
Nice!  Now I just need to be able to setup a login that is not my master login.

**Comment by VagyokC4** [comment]
Also, is it possible to adjust the placement of the save button?  I need to nudge / move it just a little bit.

![image](https://cloud.githubusercontent.com/assets/253250/13783108/335e4408-ea87-11e5-898d-d0173d75a799.png)
