### ISSUE TITLE
Ensure imported polyfills are minified

### ISSUE THREAD

**Issue by seaneking** [simplaio/simpla#33]
Seems some of the polyfills that Simpla depends on aren't being minified (eg: `promise-polyfill/Promise.js`). Ensure we're pulling minified versions, or minify it ourselves in a buildstep.

**Comment by seaneking** [comment]
Should be fixed with #37

**Comment by bedeoverend** [comment]
Also worth noting that that particular polyfill is being required by iron-ajax and potentially a few other Polymer components, which should be resolved once we move to the SDK rather than making AJAX calls from within Simpla components.

**Comment by seaneking** [comment]
Effective dupe of #49 - will be using babel transforms for minor polyfills, and not bundling wc polyfill at all. Closing in favour of that issue.
