### ISSUE TITLE
Warn when offline

### ISSUE THREAD

**Issue by seaneking** [simplaio/simpla#38]
Simpla should show a warning banner when a user is in edit mode and have dropped their connection, and not allow them to try and save until they’re back online.

Can do this by either listening to online/offline window events, or using the network info API

```
// Online/offline events.
window.addEventListener('online', e => {
  console.assert(navigator.onLine)
});

window.addEventListener('offline', e => {
  console.assert(!navigator.onLine)
});

// Network Information API
navigator.connection.addEventListener('change', e => {
  console.log(navigator.connection.type,
              navigator.connection.downlinkMax);
});
```

**Comment by bedeoverend** [comment]
My vote is for `sm-module-save`, even if you change it to being a UI-less (and `sm-module-save` reads from it and notifies or something), unless there's a good reason for Simpla elements to know about changes between offline and online, I don't think it should be in the core.

**Comment by seaneking** [comment]
This should definitely be handled by the new [`simpla-admin`](https://github.com/SimplaElements/simpla-admin) component, will move this issue there.

**Comment by seaneking** [comment]
https://github.com/SimplaElements/simpla-admin/issues/9
