### ISSUE TITLE
SPA Framework support -> Adjust location of save button

### ISSUE THREAD

**Issue by VagyokC4** [simplaio/simpla#4]
Is it possible to adjust the placement of the save button?  I need to nudge / move it just a little bit.

![image](https://cloud.githubusercontent.com/assets/253250/13783157/6a989450-ea87-11e5-9ba4-3db2ee4865e1.png)

![image](https://cloud.githubusercontent.com/assets/253250/13783108/335e4408-ea87-11e5-898d-d0173d75a799.png)

**Comment by bedeoverend** [comment]
@VagyokC4 in the future we'll look into making our admin elements (login modal, save button etc.) more flexible by separating them out from sm-admin, but we don't have any ETA for this right now

**Comment by seaneking** [comment]
You can now specify your own frontend for Simpla when initialising a project, like so:

```js
Simpla({
  project: 'PROJECT-KEY',
  elements: [
   '/path/to/custom/admin-element.html',
   '/bower_components/simpla-text/simpla-text.html',
    ...
  ]
});
```

To just move the buttons around you could fork [sm-admin](https://github.com/SimplaElements/sm-admin) and adjust styling to suit.
