### ISSUE TITLE
Multi-user support

### ISSUE THREAD

**Issue by VagyokC4** [simplaio/simpla#5]
Now I just need to be able to setup a login (for a project) that is not my master login, so that content creators can create content, and I don't have to worry about them logging into my dashboard.

**Comment by bedeoverend** [comment]
@VagyokC4 this is definitely on the roadmap, though no solid ETA yet, we'll keep you updated!

**Comment by VagyokC4** [comment]
Can we get a token or something to give out so that we can have others use this without giving out the master password?  What is the ETA on this?

**Comment by seaneking** [comment]
@VagyokC4 we'll be handling this use-case with a multi-user setup on simpla.io. So you could create a Simpla account for your content creator and then share your project with them. Once we introduce billing this would also be how you pass on the costs for a project to another user (eg: for client work). 

As @bedeoverend mentioned no hard ETA on mulit-user, but it's locked in as the next feature we build after repeatable content, so will be implemented in the near future.

**Comment by VagyokC4** [comment]
Awesome.. I look forward to testing this feature :)

**Comment by seaneking** [comment]
Just a quick update - multi-user is the top item in our backlog on the [public roadmap](https://trello.com/b/tZEZa1rN/simpla-public-roadmap), will be starting work on it soon.

**Comment by seaneking** [comment]
This is now shipped in the [new simpla.io](http://blog.simpla.io/simpla-io-v2-beta/) :-)
