### ISSUE TITLE
Hitting backspace whilst editing text often results in going back a page

### ISSUE THREAD

**Issue by giorgiodoueihi** [simplaio/simpla#6]
See title. Often happens when the simpla-text is empty (i.e., the placeholder is showing). Results in lost work.

Perhaps disallowing the backspace button to go back whilst editing (is this possible? I don't know web development).

**Comment by seaneking** [comment]
I imagine what we'd have to do is check if simpla-text is empty, and if so then intercept backspaces. 

We should also throw up a confirmation dialogue if you try to leave the page with unsaved changes, which is good practice regardless and would protect against these kinds of edge cases in future.

/cc @bedeoverend

**Comment by bedeoverend** [comment]
@giorgiodoueihi thanks - so there should be two checks for this. The major overarching one as @seaneking mentioned is asking the user if they want to lose unsaved changes when edits have been made. This should be done at a global level.

The second, which is specific to `simpla-text` should check keystrokes and prevent default behavior _if_ hitting backspace would do nothing to the text itself e.g. already empty text.

**Comment by seaneking** [comment]
Going to open an issue on simpla-text for this and another here for for warning on unsaved changes

**Comment by seaneking** [comment]
See https://github.com/simplaio/simpla/issues/13 and https://github.com/SimplaElements/simpla-text/issues/19
