### ISSUE TITLE
Move elements to this org (simplaio)

### ISSUE THREAD

**Issue by seaneking** [simplaio/simpla#85]
Now that Simpla is becoming a community driven project, it makes a lot of sense for everything to have one home, rather than half the project spread over the simplaio org and the [SimplaElements](https://github.com/SimplaElements) org. 

Makes contributing more straightforward, and cleans up the ecosystem. Maybe once the project is 100% NPM we could even look at a monorepo approach. But that's a discussion for another day.

~~What do we think?~~

### Transfers

- [x] simpla-text
- [x] simpla-img
- [x] simpla-article
- [x] simlpla-collection
- [x] simpla-link
- [x] simpla-admin
- [x] simpla-notify
- [x] simpla-markdown
- [x] simpla-path
- [x] simpla-styles
- [x] simpla-demo-helper

### Other tasks

- [x] Test bower install (repo format)
- [x] Test bower install (registry format)
- [x] Update element catalogue

### Notes

- Do we want to split simpla-richtext-behavior into a general JS module, since it's not actually tied to Simpla?

- Do we want to bundle simpla-element-behavior into the core library?

**Comment by seaneking** [comment]
Worth noting: transferring a repo via Github maintains redirects for Bower and co, so no problems there

**Comment by bedeoverend** [comment]
I don't see any issues here, and definitely all for bringing together in one home 👍

**Comment by seaneking** [comment]
Cool, will start migrating

**Comment by seaneking** [comment]
Putting a hold on this until we figure out what the deal with JS elements is. If we're going to rebuild them all in JS (ie: not using Polymer, or living dangerously and jumping straight to Polymer 3), then I motion to make [simpla-elements](https://github.com/simplaio/simpla-elements) a monorepo of them, as well as the webcomponents.org listing catalogue.

**Comment by seaneking** [comment]
Decided to do this anyway

**Comment by bedeoverend** [comment]
@seaneking as in a monorepo or just moving into separate repos?

**Comment by bedeoverend** [comment]
Oh never mind - see they're already transferred over. Down the track when / if we do all JS, I'd still be keen for a monorepo approach 👍

**Comment by seaneking** [comment]
Ha yeah just transferring, can't exactly do a monorepo w/ Bower

**Comment by seaneking** [comment]
And from our discussions sounds like all-JS is still a way off, sooo...
