### ISSUE TITLE
Adapters for the Simpla Backend

### ISSUE THREAD

**Issue by simplygreatwork** [simplaio/simpla#92]
Does the entire backend for Simpla require Netlify or only for authentication and authorization? Does Simpla communicate with Github directly or through Netlify? When I evaluate software, I am always looking at the portability factors from a non-funded perspective. I know that I can dig around to find these answers myself. Maybe a little later - but I wanted to ask you.

**Comment by madeleineostoja** [comment]
Simpla requires a) a way to authenticate users, and b) somewhere to store content. Right now authentication is done via an adapter (eg: Netlify, [Firebase](https://www.npmjs.com/package/simpla-firebase-auth), others in future), and storage is hard coded to Github. We want to open up storage to being an adapter too (see #77), so Simpla isn't tied to any particular service.
